syntax = "proto3";

package enquiry;

service CreateEnquiryService {
  rpc InitCreateEnquiry (InitCreateEnquiryRequest) returns (InitCreateEnquiryResponse);
}

message InitCreateEnquiryRequest {
  DateTime date = 1;
  string type = 2;
  int32 guests = 3;
  string space = 4;
  string venue = 5;
  string organization = 6;
  bool own_catering = 7;
  bool require_catering = 8;
  bool flexible_time = 9;
  repeated CateringOption catering_options = 10;
  string user = 11;
  string inbox = 12;
}

message InitCreateEnquiryResponse {
  string confirmation = 1;
  bool acknowledged = 2;
  string insertedId = 3;
}

message DateTime {
  string date = 1;
  string from = 2;
  string to = 3;
  Timestamp timestamp = 4;
}

message Timestamp {
  string start_date_time = 1;
  string end_date_time = 2;
}

message CateringOption {
  string name = 1;
  bool value = 2;
}
