import * as dotenv from "dotenv";
dotenv.config();

export const MONGO_URI = (process.env.MONGO_URI || "mongodb://localhost:27017") as string;
export const MONGO_DB = (process.env.MONGO_DB || "default") as string;
export const MONGO_DB_DEV = (process.env.MONGO_DB_DEV || `${process.env.MONGO_DB}-dev`) as string;
export const PORT = Number(process.env.PORT || 3001);
export const SECRET_KEY = (process.env.SECRET_KEY || "SECRETS123") as string;
export const isDev = process.env.NODE_ENV !== "production";
export const isTest = process.env.NODE_ENV === "test";
export const IS_QUEUE_MICROSERVICES = process.env.IS_QUEUE_MICROSERVICES === "true";
export const IS_BOOKING_MICROSERVICES = process.env.IS_BOOKING_MICROSERVICES === "true";
export const IS_ENQUIRY_MICROSERVICES = process.env.IS_ENQUIRY_MICROSERVICES === "true";
export const MAILER_TRANSPORT_HOST = process.env.MAILER_TRANSPORT_HOST as string;
export const MAILER_TRANSPORT_PORT = Number(process.env.MAILER_TRANSPORT_PORT || 465);
export const MAILER_TRANSPORT_SECURE = process.env.MAILER_TRANSPORT_SECURE === "true";
export const MAILER_EMAIL = process.env.MAILER_EMAIL as string;
export const MAILER_PASSWORD = process.env.MAILER_PASSWORD as string;
export const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET as string;
export const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET as string;
export const ACCESS_TOKEN_EXPIRY = process.env.ACCESS_TOKEN_EXPIRY as string;
export const REDIS_HOST = process.env.REDIS_HOST as string;
export const REDIS_PORT = Number(process.env.REDIS_PORT || 6379);
export const REDIS_PASSWORD = process.env.REDIS_PASSWORD as string;
export const SERVICE_ACCOUNT = process.env.SERVICE_ACCOUNT as string;
export const SECRETS = process.env.SECRETS as string;
export const GOOGLE_REDIRECT_URI = process.env.GOOGLE_REDIRECT_URI as string;
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID as string;
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET as string;
export const GOOGLE_AUTH_URI = process.env.GOOGLE_AUTH_URI as string;
export const ACCESS_KEY_AWS = process.env.ACCESS_KEY_AWS as string;
export const SECRET_KEY_AWS = process.env.SECRET_KEY_AWS as string;
export const REGION_AWS = process.env.REGION_AWS as string;
export const S3_BUCKET_NAME = process.env.S3_BUCKET_NAME as string;
export const DO_ENDPOINT = process.env.DO_ENDPOINT as string;
export const CDN_ENDPOINT = process.env.CDN_ENDPOINT as string;
export const BUCKET_PROTOCOL = (process.env.BUCKET_PROTOCOL as string) || "https://";
export const SERVER_ROOT_URI = process.env.SERVER_ROOT_URI as string;
export const VENUE_4_USE_URI = process.env.VENUE_4_USE_URI as string;
export const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY as string;
export const PLATFORM_FEE = process.env.PLATFORM_FEE as string;
export const COMMISION_FEE = process.env.COMMISION_FEE as string;
export const ACCESS_TOKEN_EXPIRES = (process.env.ACCESS_TOKEN_EXPIRES as string) || "10s";
export const REFRESH_TOKEN_EXPIRES = (process.env.REFRESH_TOKEN_EXPIRES as string) || "1m";
export const SITEURL = (process.env.SITEURL as string) || "http://localhost:3000";
export const STRIPE_WEBOOK_SECRET_ACCOUNT = process.env.STRIPE_WEBOOK_SECRET_ACCOUNT as string;
export const STRIPE_WEBOOK_SECRET_ACCOUNT_CONNECTED = process.env.STRIPE_WEBOOK_SECRET_ACCOUNT_CONNECTED as string;
export const SUPPORT_EMAIL = process.env.SUPPORT_EMAIL as string;
export const CC_SUPPORT_EMAIL = process.env.CC_SUPPORT_EMAIL as string;
export const DEBUG_EMAIL = process.env.DEBUG_EMAIL as string;
export const RATE_LIMITER = Number(process.env.RATE_LIMITER || 1000);
export const BOOKING_URL = (process.env.BOOKING_URL as string) || "0.0.0.0:50051";
export const QUEUE_URL = (process.env.QUEUE_URL as string) || "0.0.0.0:50052";
export const ENQUIRY_URL = (process.env.ENQUIRY_URL as string) || "0.0.0.0:50053";
export const EMAIL_STRIPE_NOTIFICATION = process.env.EMAIL_STRIPE_NOTIFICATION === "true";

export const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID as string;
export const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY as string;
export const AWS_REGION_AWS = process.env.AWS_REGION_AWS as string;
export const AWS_S3_BUCKET_NAME = process.env.AWS_S3_BUCKET_NAME as string;

export const API_URL = (process.env.API_URL as string) || "http://localhost:3001";
